%{
readstimframes_ribbit

Example script to read timings from stimulus record file and find corresponding frame numbers

Notes:
- Please put Thorsync files in same folder as ThorImage files
  (i.e. "Experiment.xml" and "Episode001.h5" needs to be in same folder)
- Stimulus timings generated from the RibbitStim scripts are stored in 
  "StimulusData_(date+time).mat" in the variables "stimtimes" and "blanktimes"
  (both are 2 column variables, column 1 = start times, column 2 = end times)

Output: 
stimframes_start = frame numbers for start of each stim
stimframes_end = frame numbers for end of each stim
blankframes_start = frame numbers for start of each blank
blankframes_end = frame numbers for end of each blank


versions
2023.3.17 VL
Can be used on stimulus records generated by loomstim_trig.m and
ovals_coherent_trig(post 2023.3.6 update)

%}

%% ------Fill in paths to experiment files----------

%stimulus timing data
stimdatapath = 'F:\Cynthia data\GCaMP data coherence dots 2023';
stimdataname = 'StimulusData_20230227_10.54.mat';

%ThorImage and ThorSync files
thorimagepath = 'F:\Cynthia data\GCaMP data coherence dots 2023\dots1';

%Index of slice to look at
crtslice = 4;

%% ------end of user input----------

%Read metadata from ThorImage "Experiment.xml" and frame data from ThorSync "Episode001.h5"
[Steps,Flyback,Frames,ftimes,CaptureRate] = ReadThorMetadata(thorimagepath);
totslice = Steps + Flyback;

%Read timings from stimulus record file
%Start and end of stimuli are recorded in "stimtimes"
load(fullfile(stimdatapath, stimdataname));

%Match stim timings with frame numbers
stimframes_start = FindStimFrame(stimtimes(:,1),ftimes,crtslice,totslice);

stimframes_end = FindStimFrame(stimtimes(:,2),ftimes,crtslice,totslice);

blankframes_start = FindStimFrame(blanktimes(:,1),ftimes,crtslice,totslice);

blankframes_end = FindStimFrame(blanktimes(:,2),ftimes,crtslice,totslice);
